export const authActions = {

    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

    SIGNUP_USER: "SIGNUP_USER",
    SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
    SIGNUP_USER_FAIL: "SIGNUP_USER_FAIL",

    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

    GET_USER: "GET_USER",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAIL: "GET_USER_FAIL",

    LOGOUT_USER: "LOGOUT_USER",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",

}